// <auto-generated />
namespace TvTamer.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlternateNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlternateNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201509301509175_AlternateNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
